client/screens/Home.js, client/screens/LoginPage.js
Registration, Login & Sign Out functionality added, few bugs causing error in redirect at the moment
=> Angel dev login

client/App.js, client/screens/LoginPage.js, client/screens/ProfilePage.js
=> registration, login, and signout added

client/App.js, client/screens/LoginPage.js
bugs fixed, redirects from signup/login to profile and back working. Please check
=> registration, login, signout working

client/App.js, client/package-lock.json, client/package.json, client/screens/LandingPage.js, client/screens/LandingPageStyles.js, package-lock.json
=> updated landing page with redirect to login

.github/ISSUE_TEMPLATE/feature_request.md, client/.github/ISSUE_TEMPLATE/bug_report.md, client/.github/ISSUE_TEMPLATE/epic-issue-template.md, client/.github/ISSUE_TEMPLATE/feature_request.yml, client/.github/PULL_REQUEST_TEMPLATE.md, client/App.js, client/screens/LoginPage.js, client/screens/LoginPageStyles.js
ternary expression functional and switching between login and registration working
=> toggle between register login

client/App.js, client/screens/LandingPageStyles.js, client/screens/LoginPageStyles.js, client/screens/ProfilePage.js, client/screens/ProfilePageStyles.js
Check code to for page layout issues. Should be ready for code
=> Profile page layout ready for code functionality

client/app.json, client/metro.config.js, client/screens/HomePage.js, client/screens/ProfilePage.js, client/tailwind.config.js, client/tailwind.css, client/tailwind.json
1. Added buttons to compliment the swipe features. A user can either swipe for a MATCH/PASS or select a button that will match the intended swipe action with the use of the 'useRef' React hook.
2. Small css change to add shadow to player card with stylesheets
_Describe the problem or feature in addition to a link to the issues._
Created touchable opacity buttons to go along with the swipe features. The main layout and core features of the home/main page are complete. 
Next steps would be to replace the dummy data with real firebase data but for layout purposes, this seems to be done. 
_Links to blog posts, patterns, libraries or addons used to solve this problem_
Docs and References
[React Native Swiper Feature …
=> Issue#16 angelb homepage layout

client/App.js
1. Added icons to nav bar
Added icons the user can tap to navigate screens
utilized react-native-elements for the icons
https://reactnativeelements.com/
Closes #18
=> added icons

client/screens/ProfilePage.js
1. Added functionality to allow uploading and saving images into Firebase
To allow a user to store profile images on storage database with firebase
Created functions that allows images to be stored on the firebase storage server where previously, images would not yet be saved. 
Please run on emulator or phone and upload an image. Then check firebase storage to make sure image is succesfully uploaded. (NOTE: Image will be gone once refreshed but still be stored on Firebase. Next PR should include retrieving stored image. ) 
https://github.com/expo/examples/blob/master/with-firebase-storage-upload/App.js
https://firebase.google.com/docs/storage/web/upload-files
=> Issue #21 - Functionality added to add images to firebase

client/screens/ProfilePage.js
1. added a structure to firebase storage ref to be able to pull data/images easier
modified the reference path to create a folder in firebase storage and the images with the userId attached
=> added file structure to firebase storage for images

client/App.js, client/screens/MatchPage.js, client/screens/MatchPageStyles.js
1. Added a match page and match page styles.
2. Added and edited App.js 
Regarding issue #45
=> added match page

client/package-lock.json, client/screens/ProfilePage.js
1. Added working text inputs that can change profile info directly to Firebase.
2. User name and location automatically updated on the profile page.
To update firebase on changes of the user fields: location, bio, username. 
Implemented the "useIsFocused" built-in react navigation function.
=> added functional profile inputs that register to firebase

client/App.js, client/screens/HomePage.js
1. Fixed an issue from a previous merge that shows two HomePage Tab SCreens and causes an error
Removed duplicate code that caused an error on app
=> Ab issue#38 - Chore(App.js) duplicated tabscreen

client/screens/HomePage.js
1. dummy data for player cards is now replaced with real user data from firebase
added a function inside useEffect to return the user data inside of our project firebase and set it inside of state to use for the swiper prop to render the player cards with real user info
Cards now use real data as opposed to previously used dummy local data
Create a new account and fill in user info with information, then check to see if card is displayed properly in home page with the right information
=> added function in useEffect on HomePage to return firebase user data into state

client/App.js, client/screens/ProfilePage.js
Added icons to the tab bar on profile page .
To be able navigate through screens.
=> added icons for tabbar profile and app.js file

client/App.js, client/Firebase/firebase.js, client/screens/HomePage.js, client/screens/ProfilePage.js
1. Changed app database from realtime database to firestore for future app functionality 
Changed our database to firestore to make use of firestores collection based db to implement a matching functionality that would potentially make it easier with collections for us
=> Firebase firestore db switch, no issue #

client/App.js, client/components/MessageRow.js, client/package-lock.json, client/screens/MatchPage.js, client/screens/MatchPageStyles.js
1. Edited the layout of the MatchPage.js
2. Resized images
Match with other users and show user profiles matched.
=> #45-matchpage-layout

client/App.js, client/package-lock.json, client/package.json, client/screens/HomePage.js
Added tab screen ant design and change font color
Users able to navigate from one screen to another
=> st#22-profilefirebase

client/components/MessageRow.js, client/components/ReceiverMessage.js, client/components/SenderMessage.js, client/input.css, client/package.json, client/screens/ChatRoom.js, client/tailwind.config.js
1. Added the ability for 2 matched users to have a messaging conversation 
created a sendMessage function to create a 'messages' collection inside of matches by matchid and a useEffect with a listener (onSnapshot) queried so that all messages will be retrievable in desc order in realtime.
Test on 2 separate accounts that have matched and send messages to each other to confirm messages are correctly sent and displayed
_If this closes an issue, name it here. If it doesn't, remove this line_
Closes #25
=> Ab issue#25  added messaging functionality

client/package.json, client/screens/HomePage.js
Added logo match page 
Styling
=> added logo match page

client/components/ReceiverMessage.js, client/components/SenderMessage.js, client/input.css, client/package-lock.json, client/package.json, client/screens/ChatRoom.js, client/screens/HomePage.js, client/screens/MatchPage.js, client/tailwind.css, client/tailwind.json
Fixed Tailwind unsupported classes error and applied styling to messenger
Fixed the error to allow us to use tailwind properly
=> ab-fixed tailwind errors and added styling to messenger-issue#none

client/App.js, client/components/ReceiverMessage.js, client/components/SenderMessage.js, client/input.css, client/package-lock.json, client/package.json, client/screens/ChatRoom.js, client/screens/HomePage.js, client/screens/MatchPage.js, client/tailwind.css, client/tailwind.json
Added conditional rendering to the navbar
Made it so if a user is logged in, they can't interact with the navbar and are limited to logging, if a user is authenticated , they will bypass the login screen and automatically be shown the appropriate screens and not the entire navbar
_If this closes an issue, name it here. If it doesn't, remove this line_
Closes #55
=> Ab issue#55 navbarfix

client/App.js, client/package-lock.json, client/screens/ProfilePage.js
1. Cleaned up profile page setting.
2. Fixed navigation of user.
General fixing up of the app
=> cleaned up profile page and app stack

client/components/MessageRow.js, client/screens/ChatRoom.js, client/screens/HomePage.js, client/screens/MatchPage.js, client/screens/MatchPageStyles.js, client/screens/ProfilePage.js, client/screens/ProfilePageStyles.js, client/tailwind.css, client/tailwind.json
1. Fixed wrong user image showing on messenger
2. Made some styling consistent across pages(header titles)
=> minor bug fixes before demo

client/App.js, client/components/MessageRow.js, client/screens/ChatRoom.js, client/screens/ProfilePage.js, client/tailwind.css, client/tailwind.json
1.Added last message preview shown from the match list
2. Changed header padding on chatroom screen
Matches in chat list will contain a preview message of the last message sent if there was a previous interaction, otherwise it will show text saying "Say Hi!"
=> Ab messengerlast message
